# Generated by Django 6.0.5 on 2026-05-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('water_depth', models.FloatField()),
                ('rain_volume', models.FloatField()),
                ('flood_risk', models.CharField(choices=[('safe', 'Safe'), ('warning', 'Warning'), ('flood', 'Flood')], default='safe', max_length=10)),
                ('flood_probability', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
