# Generated by Django 6.0.5 on 2026-05-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='wind_direction',
            field=models.CharField(default='N', max_length=10),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='wind_speed',
            field=models.FloatField(default=0.0),
        ),
    ]
